dist: trusty
sudo: required
language: node_js
node_js:
  - "10.16.2"
cache:
  directories:
    - node_modules
addons:
  chrome: stable
env:
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

install:
  - yarn
  - npm run install-chromium

script:
  - npm test
