dist: trusty
sudo: required
language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
env:
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install: if [[ `npm -v` != 6* ]]; then npm i -g npm@6; fi

install:
  - npm install -g bower
  - npm install
  - bower install
  - npm run install-chromium

script:
  - npm test
